
PROJ_FOLDER=$(grep ^AIRFLOW_PROJ_DIR env_var | cut -d'=' -f2)
DAGS_FOLDER=${PROJ_FOLDER}/dags
LOGS_FOLDER=${PROJ_FOLDER}/logs
CONFIG_FOLDER=${PROJ_FOLDER}/config
PLUGIN_FOLDER=${PROJ_FOLDER}/plugins
TASKOUT_FOLDER=${PROJ_FOLDER}/taskout

mkdir -p ${PROJ_FOLDER}
mkdir -p ${DAGS_FOLDER} ${LOGS_FOLDER} ${CONFIG_FOLDER} ${PLUGIN_FOLDER} ${TASKOUT_FOLDER}
